name: Coverage Badge
on:
  push:
    branches: [ main, master ]
  pull_request:
permissions:
  contents: write
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e . pytest pytest-cov pyyaml psutil tomli
      - run: pytest -q --cov=writetofillet --cov-report=xml
      - run: python scripts/gen_coverage_badge.py coverage.xml badges/coverage.svg
      - name: Commit badge
        run: |
          if git status --porcelain | grep badges/coverage.svg; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add badges/coverage.svg
            git commit -m "chore(badge): update coverage badge"
            git push
          else
            echo "No badge changes."
