name: Coverage Badge
on:
  push:
    branches: [ main, master ]
  pull_request:
permissions:
  contents: write
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          # Ensure we have a branch instead of detached HEAD so we can push
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e . pytest pytest-cov pyyaml psutil tomli
      - run: pytest -q --cov=writetofillet --cov-report=xml
      - run: python scripts/gen_coverage_badge.py coverage.xml badges/coverage.svg
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage.xml
            badges/coverage.svg
      - name: Commit badge
        if: github.event_name == 'push'
        run: |
          if git status --porcelain | grep -q -- 'badges/coverage.svg'; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add badges/coverage.svg
            git commit -m "chore(badge): update coverage badge"
            # Push to the current ref name explicitly (avoid detached HEAD issues)
            git push origin HEAD:${GITHUB_REF_NAME}
          else
            echo "No badge changes."
          fi
