name: Coverage Badge

on:
  push:
    branches: [ main ]

concurrency:
  group: coverage-badge-main
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  badge:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest pytest-cov pyyaml psutil tomli

      - name: Run tests with coverage
        run: |
          pytest -q --cov=writetofillet --cov-report=xml

      - name: Generate badge
        run: |
          mkdir -p badges
          python scripts/gen_coverage_badge.py coverage.xml badges/coverage.svg

      - name: Commit & push badge to main (only if changed)
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Ensure we're actually on main tracking origin/main
          git checkout main
          git pull --ff-only origin main

          git add badges/coverage.svg

          if git diff --cached --quiet; then
            echo "No badge changes."
            exit 0
          fi

          git commit -m "chore(badge): update coverage badge [skip ci]"
          git push origin HEAD:main
