name: Packagers Verify
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  brew-verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Brew install from formula
        run: |
          brew install ./Formula/writetofillet.rb
          writetofillet --version
  scoop-verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Scoop
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
      - name: Scoop install from manifest
        shell: powershell
        run: |
          scoop install $pwd\bucket\writetofillet.json
          writetofillet --version

