name: Packagers Verify
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  brew-verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Brew install from local tap
        shell: bash
        run: |
          set -euo pipefail
          # Create a temporary local tap and copy the formula into it
          brew tap-new local/writetofillet >/dev/null
          tapdir="$(brew --repository)/Library/Taps/local/homebrew-writetofillet"
          mkdir -p "$tapdir/Formula"
          cp Formula/writetofillet.rb "$tapdir/Formula/writetofillet.rb"
          # Install from the local tap by name, not path
          brew install local/writetofillet/writetofillet
          writetofillet --version
  scoop-verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Scoop
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
          # Ensure Scoop shims are on PATH for subsequent steps
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding ascii -Append
      - name: Scoop install from manifest
        shell: powershell
        run: |
          scoop install $pwd\bucket\writetofillet.json
          writetofillet --version
