name: Test
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e . pytest pyyaml psutil tomli
      - run: pytest -q
